### ISSUE TITLE
Kies een teamleider en zet dit in README

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/Team-Universe#10]
Ik wil graag zien wie de teamleider is.

De teamleider zorgt ervoor dat iedereen fijn kan samenwerken.

**Comment by ProfRedRooster** [comment]
rohan

**Comment by richelbilderbeek** [comment]
Uhh, ik herhaal:

> zet dat in README

Succes :+1:

**Comment by richelbilderbeek** [comment]
Uhh, ik herhaal:

> zet dat in README

Succes :+1:
