### ISSUE TITLE
Kies een voorzitter en zet dat in README

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/Team-Universe#12]
Ik wil graag zien wie de voorzitter is.

De voorzitter bepaalt de regels van een vergadering.

**Comment by ProfRedRooster** [comment]
Rohan

**Comment by ProfRedRooster** [comment]
Quinn

**Comment by ProfRedRooster** [comment]
Daan

**Comment by richelbilderbeek** [comment]
Uhh, ik herhaal:

> zet dat in README

Succes :+1:

**Comment by richelbilderbeek** [comment]
Uhh, ik herhaal:

> zet dat in README

Succes :+1:
